<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tipo_socio", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit tipo_socio
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "tipo_socio/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTipoSocioId" class="col-sm-2 control-label">Tipo Of Socio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipo_socio_id", "type" => "number", "class" => "form-control", "id" => "fieldTipoSocioId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTipoSocio" class="col-sm-2 control-label">Tipo Of Socio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipo_socio", "size" => 30, "class" => "form-control", "id" => "fieldTipoSocio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigo" class="col-sm-2 control-label">Codigo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo", "size" => 30, "class" => "form-control", "id" => "fieldCodigo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["descripcion", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivo" class="col-sm-2 control-label">Activo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activo", "size" => 30, "class" => "form-control", "id" => "fieldActivo"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
