<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search cargo
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["cargo/new", "Create cargo"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "cargo/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCargoId" class="col-sm-2 control-label">Cargo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cargo_id", "type" => "number", "class" => "form-control", "id" => "fieldCargoId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCargo" class="col-sm-2 control-label">Cargo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cargo", "size" => 30, "class" => "form-control", "id" => "fieldCargo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigo" class="col-sm-2 control-label">Codigo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo", "size" => 30, "class" => "form-control", "id" => "fieldCodigo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["descripcion", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldActivo" class="col-sm-2 control-label">Activo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["activo", "size" => 30, "class" => "form-control", "id" => "fieldActivo"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
